### ISSUE TITLE
Auto-Scroll session list to the current time.

### ISSUE THREAD

**Issue by rharter** [rharter/chicago-roboto#9]
When the user opens the app during the conference, the session list should automatically be set to the current time slot.

**Comment by JakeWharton** [comment]
#12. Doesn't select the nearest date by default yet though.

**Comment by JakeWharton** [comment]
Looks like dates are stored as Strings and not Dates. But maybe that's because Firebase. I ain't never used it so not sure if you can store real types or not...

**Comment by rharter** [comment]
They are stored as strings, available as `start_time`, but concerted to
Dates, available as `startTime`.

**Comment by rharter** [comment]
Fixed in #15
